typedef unsigned short color_t;
color_t encode_color(unsigned short r, unsigned short g, unsigned short b);
void draw_rect(int x1, int y1, int width, int height, color_t c);
int nanosleep(const struct timespec *req, struct timespec *rem);
void draw_text(int x, int y, const char *text, color_t c);
void draw_pixel(int x, int y, color_t color);
void keypress_switch(int button);
void sleep_ms(long ms);
void init_graphics();
void exit_graphics();
void clear_screen();
char getkey();